[주디] [Algorithm] README.md 목차 업데이트
devSquad-study/2023-CS-Study pull request #107
Opened 2023-03-08 13:38 UTC by ParkJungYoon

1주차 목차 업데이트 합니다!!
오늘도 아주 마라톤 그자체!

팬시 목차랑 한 번에 머지하겠습니다!! PR 아직 머지 하지 말아주세용~!

2023-03-13 12:44 UTC, ParkJungYoon commented
메인 리드미도 업데이트했습니다!! 머지 해주세용!!

2023-03-14 02:25 UTC, namtndus requested changes, later dismissed
메인 수정 확인했어요 👍

2023-03-14 02:27 UTC, namtndus commented
> 메인 수정 확인했어요 👍

2023-03-14 02:29 UTC, namtndus commented
오류가 발생했네요

2023-03-14 02:31 UTC, ParkJungYoon commented
리뷰 남길 때 approve 클릭하면 돼요!!

<img width="685" alt="스크린샷 2023-03-14 오전 11 31 05" src="https://user-images.githubusercontent.com/97580782/224877642-08a919e5-6efb-4461-a760-3c0627f5f87b.png">

2023-03-14 02:32 UTC, ParkJungYoon commented
Files changed 클릭해서 우측 상단에 보면 코멘트 제출 버튼 있습니다! 

<img width="282" alt="스크린샷 2023-03-14 오전 11 32 09" src="https://user-images.githubusercontent.com/97580782/224877751-56305eed-f076-47d2-b4d9-4b7cbefd76ba.png">

2023-03-14 02:36 UTC, namtndus approved these changes
알고리즘의 목차 내용 변경과 모의 면접의 문서를 등록한 것을 확인했습니다

2023-03-14 02:37 UTC, merged